# aphenos-core/Cargo.toml
[package]
name = "aphenos-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
blake3 = "1"
thiserror = "1"
ed25519-dalek = "1"
